export interface RenderItem {
  id: string;
  title: string;
  category: "residential" | "commercial" | "event" | "interior" | "plaza" | "football" | "terrace" | "institutional";
  categoryLabel: string;
  location: string;
  image: string;
  accentColor: string;
  specs: string[];
  description: string;
  architecturalHighlights?: string[];
}

export const RENDERS: RenderItem[] = [
  {
    id: "26",
    title: "Modern 5-Bedroom Luxury Residence — Alternative Material Finish & Timber Screen Elevation",
    category: "residential",
    categoryLabel: "RESIDENTIAL ARCHITECTURE · MATERIAL EXPLORATION",
    location: "LEKKI PHASE 1 / OGUN-LAGOS RESIDENTIAL CORRIDOR, NIGERIA",
    image: "/renders/modern_5bed_alternative_materials.jpg",
    accentColor: "#efc558",
    specs: [
      "5 En-Suite Master Bedrooms with Private Ante-Rooms & Balconies",
      "Alternative Material Expression: Natural Timber Screening & Cedar Soffit Cladding",
      "Sculpted Angular Cantilever Upper Deck with Perimeter LED Strip Contour",
      "Double-Height Curtain Wall Glass Stairwell with Suspended Pendant Light",
      "Bespoke Fluted Hardwood Entrance Pivot Door with Dual Ironmongery Handles",
      "Interlocked Stone Driveway Courtyard with Cypress & Exotic Foliage Landscaping",
    ],
    description:
      "A flagship architectural material exploration of the modern 5-bedroom luxury residence, incorporating rich vertical timber privacy screens, warm wood-paneled cantilever soffits, continuous linear LED contour illumination, a soaring double-height glass stairwell, and tailored dusk landscaping.",
    architecturalHighlights: [
      "Alternative material exploration pairing natural hardwood timber slats and cedar soffits with crisp white render",
      "Sculpted continuous linear LED contour illumination framing the cantilevered second-story balcony and ground entryway",
      "Double-height acoustic glass curtain wall revealing the sculptural interior floating staircase",
      "Custom-crafted solid hardwood entrance pivot door accented by vertical architectural handle hardware",
      "Integrated multi-tier exterior lighting including perimeter wall sconces, step strip lights, and cypress garden uplights",
    ],
  },
  {
    id: "24",
    title: "Modern 5-Bedroom Luxury Bungalow Villa — Daytime Facade & Grand Portico",
    category: "residential",
    categoryLabel: "LUXURY RESIDENTIAL BUNGALOW",
    location: "LEKKI PHASE 1 / OGUN-LAGOS RESIDENTIAL CORRIDOR, NIGERIA",
    image: "/renders/modern_5bed_bungalow_day.jpg",
    accentColor: "#efc558",
    specs: [
      "5 En-Suite Master Bedrooms with Private Ante-Rooms",
      "Double-Height Grand Entrance Portico with Crystal Chandelier",
      "Architectural Perimeter Soffit LED Strip Wash & Wall Sconces",
      "Monolithic Vertical Fin Wall & Slim Window Framing",
      "Wet-Paved Polished Courtyard Driveway with Garden Bedding",
      "Subtropical Landscape Planters with Exotic Palms & Monsteras",
    ],
    description:
      "A state-of-the-art 5-bedroom modern luxury bungalow masterplan featuring a high-impact vertical architectural fin wall, cantilevered grand entrance porch adorned with a crystal chandelier, vertical recessed slim window glazing, and wet-paved courtyard driveway framed by tropical monstera foliage.",
    architecturalHighlights: [
      "Monolithic vertical architectural fin wall anchoring the front elevation symmetry",
      "Cantilevered entrance canopy featuring an opulent multi-tier crystal chandelier and recessed spotlights",
      "Perimeter linear LED under-soffit warm wash and dual-beam exterior wall sconces",
      "Integrated lush garden beds featuring monstera plants, potted palms, and ground cover up-lighting",
      "High-durability white rendered facade with moisture-resistant architectural soffit capping",
    ],
  },
  {
    id: "25",
    title: "Modern 5-Bedroom Luxury Bungalow Villa — Evening Warm LED Illumination",
    category: "residential",
    categoryLabel: "LUXURY RESIDENTIAL BUNGALOW",
    location: "LEKKI PHASE 1 / OGUN-LAGOS RESIDENTIAL CORRIDOR, NIGERIA",
    image: "/renders/modern_5bed_bungalow_evening.jpg",
    accentColor: "#d4a843",
    specs: [
      "5 En-Suite Master Bedrooms with Private Ante-Rooms",
      "Warm Soffit & Pillar Architectural Lighting Scheme",
      "Illuminated Entrance Porch with Crystal Chandelier Glow",
      "Perimeter Wall Sconces & Landscape Up-Lighting",
      "High-Index Reflective Wet-Paved Courtyard Paving",
      "Integrated Security Access & Subtropical Hedge Border",
    ],
    description:
      "An evening architectural rendering of the 5-bedroom luxury bungalow highlighting the warm linear LED soffit illumination, perimeter garden up-lighting, crystal chandelier ambient glow, and floating vertical architectural fin structure.",
    architecturalHighlights: [
      "Dramatic warm architectural LED wash illuminating facade soffits, entrance porch, and ground-level perimeter",
      "Multi-tier crystal chandelier casting an opulent warm glow through the grand entrance canopy",
      "Strategic dual-beam vertical wall sconces highlighting white architectural render textures",
      "Specular wet-paved courtyard reflection amplifying twilight sky contrast and facade lighting",
    ],
  },
  {
    id: "23",
    title: "Luxury Boutique Hotel & Resort Pool — High-Angle Aerial Spatial View",
    category: "event",
    categoryLabel: "LUXURY HOSPITALITY & HOTEL RESORT",
    location: "VICTORIA ISLAND WATERFRONT / LEKKI PHASE 1, NIGERIA",
    image: "/renders/luxury_hotel_pool_resort.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Multi-Tiered White Hotel Balconies with Potted Palms",
      "Turquoise Swimming Pool with Submerged Lounger Deck",
      "Striped Sun Umbrellas & Al Fresco Dining Courtyard",
      "Dark Tiled Gazebo Roofs & Tropical Landscaping",
      "Integrated Linear Perimeter Lighting & Paved Walkways",
      "Private Balcony Glass Balustrades & Recessed Windows",
    ],
    description:
      "An aerial 3D spatial architecture view of a luxury boutique hotel and resort complex — featuring multi-tier white guestroom wings with potted palm balconies, a crystal turquoise pool with submerged sun loungers, outdoor dining cabanas under striped umbrellas, dark tiled gazebos, and subtropical landscaping.",
    architecturalHighlights: [
      "High-angle spatial masterplan detailing pool circulation, outdoor lounge cabanas, and guestroom wing integration",
      "Cantilevered private guest balconies with dark tiled flooring, safety glass balustrades, and potted palms",
      "Turquoise swimming pool featuring built-in shallow water lounger ledges and submerged steps",
      "Zoned al fresco hospitality area with orange/white striped sun umbrellas, dark timber gazebos, and lush garden beds",
      "Subtle floor-recessed LED path lights illuminating interlocked walkways and outdoor lounge zones",
    ],
  },
  {
    id: "21",
    title: "Modern Educational Campus — Nursery, Primary & Secondary Wings (Day View)",
    category: "institutional",
    categoryLabel: "EDUCATIONAL & INSTITUTIONAL ARCHITECTURE",
    location: "LEKKI PHASE 1 / OGUN-LAGOS EDUCATIONAL CORRIDOR",
    image: "/renders/modern_school_day.jpg",
    accentColor: "#efc558",
    specs: [
      "End-to-End Ecosystem Execution (Research, Branding, Digital Visibility & Spatial Design)",
      "Integrated Nursery, Primary & Secondary Academic Wings",
      "Multi-Purpose Meeting Hall & Executive Staff Room",
      "Outdoor Recreational Playground & Basketball Arena",
      "Perimeter Paved Courtyard with Burgundy Umbrella Seating",
      "Multi-Tiered External Staircases & High-Visibility Glazing",
      "Subtropical Landscaping & Outdoor Student Assembly Grounds",
    ],
    description:
      "A flagship modern educational campus masterplan delivering a complete institutional ecosystem — engineered from initial feasibility research and strategic branding to digital visibility platforms and full 3D spatial space design. Integrates Nursery, Primary, and Secondary academic wings around a vibrant recreational courtyard, featuring a dedicated multi-purpose meeting hall with staff room, equipped playground with basketball court, and seamless multi-tier circulation staircases.",
    architecturalHighlights: [
      "Turnkey institutional ecosystem integration — bridging feasibility research, strategic brand identity, digital visibility, and 3D spatial architecture",
      "Zoned multi-level academic blocks engineered for optimal student movement, ventilation, and age-group separation",
      "Integrated administrative wing hosting staff offices, executive meeting hall, and reception facilities",
      "Central landscaped recreational grounds featuring heavy-duty wooden picnic benches, shading umbrellas, swings, and sports arena",
      "High-durability white rendered facade with energy-efficient green window glazing, safety balustrades, and external staircases",
    ],
  },
  {
    id: "22",
    title: "Modern School Campus Courtyard & Assembly Grounds (Evening View)",
    category: "institutional",
    categoryLabel: "EDUCATIONAL & INSTITUTIONAL ARCHITECTURE",
    location: "LEKKI PHASE 1 / OGUN-LAGOS EDUCATIONAL CORRIDOR",
    image: "/renders/modern_school_evening.jpg",
    accentColor: "#d4a843",
    specs: [
      "Complete Institutional Ecosystem Scope (Research → Brand → Digital → Spatial)",
      "Day/Evening Courtyard Illumination & Perimeter Security Lighting",
      "Integrated Playground, Swing Structures & Basketball Hoop",
      "Staff Conference Hall & Administrative Wing Connection",
      "Low-Maintenance Interlocked Courtyard Paving & Lawn Bedding",
      "Executive Staff & Visitor Drop-off Parking Bay",
      "Safety-Compliant Perimeter Fencing & Stairwell Guardrails",
    ],
    description:
      "An evening architectural rendering of the modern school campus showcasing the full institutional ecosystem in motion — from spatial space design and ambient courtyard lighting to digital visibility systems and cohesive brand integration. Highlights outdoor student recreational amenities, staff administrative block, and a serene academic atmosphere.",
    architecturalHighlights: [
      "Comprehensive ecosystem rollout — uniting spatial space design, brand identity, digital presence, and operational spatial strategy",
      "Warm architectural accent lighting illuminating ground-level walkways, stairwells, and classroom entryways",
      "Multi-purpose outdoor recreational zone combining natural grass turf, basketball hoop, and swing sets",
      "Efficient architectural circulation connecting the staff room, meeting hall, and all three learning sections",
      "Reflective polished courtyard paving enhancing light distribution across the educational compound",
    ],
  },
  {
    id: "0",
    title: "4-Story Commercial Plaza — Front Facade & Executive Parking",
    category: "commercial",
    categoryLabel: "COMMERCIAL & SPATIAL ARCHITECTURE",
    location: "LEKKI PHASE 1 / OGUN-LAGOS CORRIDOR",
    image: "/renders/commercial_plaza_front_facade.jpg",
    accentColor: "#d4a843",
    specs: [
      "4-Story Symmetrical White Rendered Facade",
      "Automated Black Steel Perimeter Gate",
      "Executive Ground-Level Parking Bays",
      "Linear Under-Soffit Warm LED Wash",
      "Floor-to-Ceiling Anodized Shopfront Glazing",
      "Integrated Security Access Control",
    ],
    description:
      "A flagship 4-story commercial plaza front elevation featuring symmetrical architectural white framing, automated security gating, executive courtyard parking for luxury vehicles, and warm linear LED soffit illumination.",
    architecturalHighlights: [
      "Dual vertical structural towers flanking an internal pedestrian courtyard accessway",
      "High-contrast dark anodized aluminum window mullions with floor-to-ceiling double glazing",
      "Recessed perimeter wall sconces highlighting boundary security fencing and driveway paving",
      "Dedicated ground-floor retail showroom bays with unobstructed street-facing visibility",
    ],
  },
  {
    id: "20",
    title: "Modern Executive Terrace Housing Estate with Carports & Warm Accent Lighting",
    category: "terrace",
    categoryLabel: "MODERN TERRACE ARCHITECTURE",
    location: "LEKKI PHASE 1 / OGUN-LAGOS CORRIDOR, NIGERIA",
    image: "/renders/modern_terrace_residence.jpg",
    accentColor: "#efc558",
    specs: [
      "Multi-Unit Symmetrical Modern Terrace Facade",
      "Cantilevered Steel Carport Shade Structures",
      "Terracotta Accent Recessed Entry Porches",
      "Automated Steel Perimeter Fence Gating",
      "Linear Soffit Wash & Pillar Lighting",
      "Interlocked Driveway & Paved Courtyard",
    ],
    description:
      "A luxury multi-unit modern terrace housing estate featuring clean white architectural geometry, terracotta-accented recessed entryways, cantilevered steel carports, integrated perimeter pillar sconces, and lush front garden hedging.",
    architecturalHighlights: [
      "Symmetrical multi-unit terrace layout with dedicated covered parking bays for luxury vehicles",
      "High-contrast warm terracotta recessed accent walls on entry porches and upper balconies",
      "Steel frame carports with heavy-duty shade fabric and integrated pillar sconces",
      "Wet-paved interlocked driveway with illuminated perimeter hedge borders",
    ],
  },
  {
    id: "19",
    title: "Executive Multi-Unit Terrace Duplex Estate",
    category: "terrace",
    categoryLabel: "LUXURY TERRACE RESIDENCE",
    location: "LEKKI PHASE 1 / CHEVRON AXIS, NIGERIA",
    image: "/renders/luxury_terrace_duplex_estate.jpg",
    accentColor: "#d4a843",
    specs: [
      "Cantilevered Steel Carport Canopies",
      "Textured Stone Clad Boundary Wall",
      "Vertical Timber Recessed Accents",
      "Linear Under-Soffit Night Wash",
      "Integrated Perimeter Wall Sconces",
      "Executive SUV Parking Bays",
    ],
    description:
      "A prestigious multi-unit terrace duplex residence captured at twilight. Features cantilevered executive carport structures, warm soffit strip lighting, natural stone boundary cladding, and rich timber recessed entry balconies.",
    architecturalHighlights: [
      "Dual cantilevered steel carports with integrated LED downlights",
      "High-contrast timber wall panelling around upper terrace balconies",
      "Natural split-face stone cladding along perimeter security walls and garden steps",
      "Clean white rendered upper facade with warm architectural vertical wall sconces",
    ],
  },
  {
    id: "15",
    title: "Lettable Commercial Plaza & Executive Studio Suite",
    category: "commercial",
    categoryLabel: "COMMERCIAL & SPATIAL ARCHITECTURE",
    location: "PRIME BUSINESS LOCATION / OGUN-LAGOS CORRIDOR",
    image: "/renders/lettable_space_commercial_flyer.jpg",
    accentColor: "#d4a843",
    specs: [
      "4-Story Glass & LED Wash Facade",
      "Rooftop Studio Suite (5m x 6m)",
      "Warm Cove Kitchen & Bath Lighting",
      "24/7 Secure Business Environment",
      "Interlocked Courtyard Paving",
      "High-Contrast Aluminium Framing",
    ],
    description:
      "A flagship commercial building masterplan featuring premium office spaces for rent, floor-to-ceiling curtain wall glazing, interlocked paved courtyard, and an executive rooftop studio apartment with custom wood finishes and warm LED cove illumination.",
    architecturalHighlights: [
      "Cantilevered upper floor balconies with embedded linear LED strip wash",
      "Full-height acoustic curtain wall glass panels maximizing natural daylighting",
      "Executive rooftop studio suite (5m x 6m) with dedicated kitchen nook and rain-shower bath",
      "Heavy-duty interlocked stone driveway designed for high-density corporate parking",
    ],
  },
  {
    id: "1",
    title: "5-Bedroom Modern Luxury Residence",
    category: "residential",
    categoryLabel: "RESIDENTIAL ARCHITECTURE",
    location: "LEKKI PHASE 1 / OGUN-LAGOS CORRIDOR",
    image: "/renders/residential_villa_facade.jpg",
    accentColor: "#d4a843",
    specs: [
      "Cantilevered Upper Deck",
      "Linear Facade Strip Lighting",
      "Floor-to-Ceiling Glass Stairwell",
      "Bespoke Wooden Entry Pivot Door",
    ],
    description:
      "A contemporary 5-bedroom private villa defined by bold geometric cantilevers, architectural linear LED wall wash, double-height glass stairwell glazing, and secluded perimeter lighting.",
    architecturalHighlights: [
      "Floating concrete upper cantilever slab",
      "Integrated vertical timber wall cladding",
      "Hidden perimeter nightscape LED channels",
    ],
  },
  {
    id: "2",
    title: "Modern High-Rise Apartment Tower at Dusk",
    category: "residential",
    categoryLabel: "LUXURY HIGH-RISE RESIDENTIAL",
    location: "VICTORIA ISLAND WATERFRONT CORRIDOR",
    image: "/renders/highrise_luxury_apartments.jpg",
    accentColor: "#d4a843",
    specs: [
      "Multi-Tier Balcony Recessed LEDs",
      "Warm Vertical Facade Strips",
      "Reflective Wet Paving Entry Courtyard",
      "Glass Balustrade Decking",
    ],
    description:
      "A multi-level luxury apartment tower captured at dusk, boasting warm vertical strip illumination, glass balustrades, integrated lush terrace planters, and executive entrance drops.",
    architecturalHighlights: [
      "Multi-tiered terrace gardening integration",
      "High-index reflective glass envelope",
    ],
  },
  {
    id: "3",
    title: "Executive 2-Story Luxury Duplex",
    category: "residential",
    categoryLabel: "RESIDENTIAL ARCHITECTURE",
    location: "LEKKI SCHEME 2 / CHEVRON AXIS",
    image: "/renders/modern_duplex_residence.jpg",
    accentColor: "#d4a843",
    specs: [
      "Warm Under-Soffit Lighting",
      "Seamless Glass Balustrade",
      "Landscaped Garden Beds",
      "Interlocked Paved Courtyard",
    ],
    description:
      "A contemporary 2-story luxury duplex boasting integrated under-soffit architectural LED strips, tinted glass balcony railings, and lush perimeter garden beds.",
    architecturalHighlights: [
      "Integrated soffit lighting channels",
      "High-contrast dark roof parapet capping",
    ],
  },
  {
    id: "4",
    title: "Grand Foyer & Floating Staircase",
    category: "interior",
    categoryLabel: "LUXURY INTERIOR ARCHITECTURE",
    location: "PRIVATE RESIDENTIAL SANCTUARY",
    image: "/renders/foyer_staircase_interior.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Floating Tread Staircase",
      "Under-Riser Warm LED Strips",
      "Polished Marble Flooring",
      "Frameless Glass Balustrade",
    ],
    description:
      "An opulent double-height entryway featuring floating marble treads, seamless frameless glass guardrails, custom gallery artwork, and warm indirect cove ambient lighting.",
    architecturalHighlights: [
      "Cantilevered steel structural staircase stringer",
      "Book-matched Italian marble slab floor",
    ],
  },
  {
    id: "5",
    title: "Sprawling Multi-Family Residential Block",
    category: "residential",
    categoryLabel: "MULTI-FAMILY HOUSING COMPLEX",
    location: "OGUN–LAGOS SUBURBAN CORRIDOR",
    image: "/renders/multifamily_residential_block.jpg",
    accentColor: "#d4a843",
    specs: [
      "Linear Multi-Unit Block Structure",
      "Recessed Wall Sconce Lighting",
      "Wood-Accented Recessed Balconies",
      "Cobblestone Perimeter Courtyard",
    ],
    description:
      "A multi-unit residential development designed with high-density architectural symmetry, incorporating warm accent wall sconces, wood-paneled balcony niches, and cobblestone grounds.",
  },
  {
    id: "6",
    title: "Architectural Gallery & Atrium Corridor",
    category: "interior",
    categoryLabel: "COMMERCIAL INTERIOR ARCHITECTURE",
    location: "VICTORIA ISLAND COMMERCIAL TOWER",
    image: "/renders/corporate_lobby_corridor.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Double-Height Skylight Glazing",
      "Linear Acoustic Wooden Ceiling Baffles",
      "High-Gloss Polished Terrazzo",
      "Minimalist Recessed Track Spotlights",
    ],
    description:
      "A grand commercial atrium corridor utilizing natural skylight penetration, sound-absorbing timber ceiling baffles, and polished stone flooring designed for institutional prestige.",
  },
  {
    id: "7",
    title: "Modern Glass Facade Villa Estate",
    category: "residential",
    categoryLabel: "LUXURY RESIDENTIAL COMPOUND",
    location: "LEKKI PHASE 1 WATERFRONT",
    image: "/renders/glass_facade_estate.jpg",
    accentColor: "#d4a843",
    specs: [
      "Floor-to-Ceiling Panoramic Glazing",
      "Cantilevered Infinity Deck",
      "Linear Landscape Sconce Lighting",
      "Executive Entry Portico",
    ],
    description:
      "A waterfront luxury residence designed around unobstructed panoramic views, featuring floor-to-ceiling double-glazed curtain walls and architectural perimeter step lighting.",
  },
  {
    id: "8",
    title: "Twin Luxury Multi-Unit Estate",
    category: "residential",
    categoryLabel: "LUXURY RESIDENTIAL COMPOUND",
    location: "EPE EXP.-WAY / OGUN CORRIDOR",
    image: "/renders/twin_villa_estate.jpg",
    accentColor: "#d4a843",
    specs: [
      "Dual Villa Architectural Layout",
      "Terraced Entrance Porticos",
      "Contrasting Dark Pitch Roof",
      "Subtle Step Recessed Lighting",
    ],
    description:
      "A sprawling dual-villa residential estate combining classic pitch roofs with sleek modern white facade rendering, floating portico steps, and subtle ambient nightscape lighting.",
  },
  {
    id: "9",
    title: "Raw Concrete Executive Gallery Atrium",
    category: "interior",
    categoryLabel: "SPATIAL INTERIOR CONCEPTS",
    location: "ELEVATION STUDIOS HEADQUARTERS",
    image: "/renders/executive_hallway_atrium.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Architectural Cast-in-Place Concrete",
      "Integrated Sculptural Planters",
      "High-Gloss Terrazzo Flooring",
      "Warm Up-spot Lighting",
    ],
    description:
      "A sophisticated gallery atrium showcasing raw board-formed architectural concrete walls, high-gloss terrazzo floor reflections, and oversized illuminated vessel planters.",
  },
  {
    id: "10",
    title: "Luxury Event Centre & Pavilion Walkway",
    category: "event",
    categoryLabel: "HOSPITALITY & EVENT SPACES",
    location: "VICTORIA ISLAND / CORRIDOR",
    image: "/renders/event_centre_pavilion.jpg",
    accentColor: "#a89fd4",
    specs: [
      "Tensile Membrane Conical Canopies",
      "Perimeter Landscape Bollard Lights",
      "Microclimate Paving & Garden Border",
      "Al Fresco Executive Lounge Seating",
    ],
    description:
      "A flagship multi-purpose event grounds concept featuring tensioned conical canopy umbrellas, integrated storm-drain channels, and ambient outdoor garden illumination.",
  },
  {
    id: "11",
    title: "Contemporary Executive Master Suite",
    category: "interior",
    categoryLabel: "HIGH-END INTERIOR CONCEPT",
    location: "EXECUTIVE PENTHOUSE",
    image: "/renders/master_suite_interior.jpg",
    accentColor: "#e5a158",
    specs: [
      "Gallery-Grade Wall Art Curation",
      "Raw Concrete & Wood Accent Wall",
      "Teal Velvet & Linen Bedding Suite",
      "Floor-to-Ceiling Rain-Glass Wall",
    ],
    description:
      "An executive master suite blending raw textured concrete surfaces with teal velvet accents, gallery-grade artwork displays, and floor-to-ceiling acoustic glass partitions.",
  },
  {
    id: "12",
    title: "Commercial Plaza & Mixed-Use Complex",
    category: "commercial",
    categoryLabel: "COMMERCIAL & MIXED-USE PLAZA",
    location: "OGUN–LAGOS COMMERCIAL CORRIDOR",
    image: "/renders/commercial_plaza_facade.jpg",
    accentColor: "#60a5fa",
    specs: [
      "Multi-Tier Balcony Grid",
      "Twilight Architectural Uplighting",
      "Reflective Stone Courtyard Paving",
      "High-Efficiency Glazing",
    ],
    description:
      "A monumental commercial plaza and residential complex designed for high-density elegance, featuring warm facade uplighting, glass balconies, and reflective courtyard paving.",
  },
  {
    id: "13",
    title: "Modern Commercial Plaza & Indoor Atrium",
    category: "commercial",
    categoryLabel: "COMMERCIAL & MIXED-USE PLAZA",
    location: "ABUJA / LAGOS COMMERCIAL CORRIDOR, NIGERIA",
    image: "/renders/modern_plaza_indoor_atrium.jpg",
    accentColor: "#60a5fa",
    specs: [
      "4-Story Skylight Central Courtyard",
      "Linear LED Soffit Strips",
      "Frameless Storefront Glazing",
      "Integrated Digital Directory Totem",
    ],
    description:
      "A flagship 4-story commercial plaza interior atrium in Nigeria featuring a soaring skylight canopy, multi-level glass shopfront balconies, fluted store signage, and polished stone walkway paving.",
  },
  {
    id: "14",
    title: "Family Event Centre & Outdoor Dining Pavilion",
    category: "event",
    categoryLabel: "HOSPITALITY & EVENT SPACES",
    location: "VICTORIA ISLAND / OGUN CORRIDOR, NIGERIA",
    image: "/renders/family_event_centre_pavilion.jpg",
    accentColor: "#a89fd4",
    specs: [
      "Pergola Dining Pavilion Shading",
      "Double-Story Modern Event Villa",
      "Lush Perimeter Planter Wall Sconces",
      "Al Fresco Lattice Lounge Seating",
    ],
    description:
      "A serene multi-purpose family event centre and outdoor dining pavilion, boasting white architectural pergolas, green lattice terrace seating, high-contrast black glass framing, and ambient perimeter lighting.",
  },
  {
    id: "16",
    title: "Modern Commercial Plaza Store Corridor & Atrium Walkway",
    category: "plaza",
    categoryLabel: "MODERN PLAZA ARCHITECTURE",
    location: "LAGOS / ABUJA COMMERCIAL AXIS, NIGERIA",
    image: "/renders/modern_plaza_store_corridor.jpg",
    accentColor: "#d4a843",
    specs: [
      "Multi-Level Open Storefront Balconies",
      "Linear Warm Soffit Illumination",
      "Polished Cobblestone Corridor Paving",
      "Subtle Downlight Wall Sconces",
      "Integrated Store Signage & Branding",
      "Minimalist White Facade Elements",
    ],
    description:
      "A sophisticated multi-level modern commercial plaza interior featuring illuminated storefronts (Store 01, Store 02), open-air vertical atrium wells, warm linear cove lighting, polished stone walkway paving, and integrated store branding.",
    architecturalHighlights: [
      "Open-well vertical light shaft illuminating lower level retail corridors",
      "Integrated black aluminum signage boxes with warm LED backlighting",
      "Continuous linear LED under-soffit wash along all floor levels",
      "Subtropical indoor planter arrangements enhancing pedestrian atmosphere",
    ],
  },
  {
    id: "17",
    title: "Private Luxury Football Pitch — Dusk Floodlight Atmosphere",
    category: "football",
    categoryLabel: "PRIVATE FOOTBALL PITCH & SPORTS RECREATION",
    location: "PRIVATE LUXURY ESTATE / LEKKI-ABUJA CORRIDOR",
    image: "/renders/private_football_pitch_dusk.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Heavy-Duty Tubular Steel Cage Frame",
      "High-Intensity LED Perimeter Floodlights",
      "Professional Synthetic Turf Pitch",
      "Linear Wall Wash & Ground Spotlights",
      "Integrated Steel Netting Enclosure",
      "Pro-Grade Goal Posts & Ball Markings",
    ],
    description:
      "A state-of-the-art private mini football pitch within a luxury residential compound captured at sunset. Features high-tensile tubular steel cage framework, professional synthetic turf, integrated perimeter floodlighting, and warm landscape sconce illumination.",
    architecturalHighlights: [
      "Modular tubular steel structural frame engineered for wind and ball impact resistance",
      "High-efficiency perimeter LED strip wash integrated along upper structural beams",
      "Low-glare ground spotlighting illuminating interlocked spectator walkways",
      "Seamless integration into private residential villa perimeter grounds",
    ],
  },
  {
    id: "18",
    title: "Private Luxury Football Pitch — Daytime Structural Elevation",
    category: "football",
    categoryLabel: "PRIVATE FOOTBALL PITCH & SPORTS RECREATION",
    location: "PRIVATE LUXURY ESTATE / LEKKI-ABUJA CORRIDOR",
    image: "/renders/private_football_pitch_day.jpg",
    accentColor: "#4ecba0",
    specs: [
      "Polished Steel Cage Architecture",
      "All-Weather Synthetic Turf System",
      "High-Tension Anti-Rebound Mesh Netting",
      "Paved Boundary Walkway & Garden Bed",
      "Precision White Boundary Pitch Line Marking",
      "Integrated Drainage Foundation",
    ],
    description:
      "A crisp daytime elevation of the private sports arena showcasing its structural steel cage engineering, all-weather synthetic turf, white boundary markings, and landscaped perimeter border.",
    architecturalHighlights: [
      "Mirror-finish structural steel column assembly with concealed fasteners",
      "High-density UV-stabilized synthetic grass turf with shock-pad underlayment",
      "Lush garden boundary beds separating the pitch enclosure from estate walkways",
      "Multi-angle sightlines designed for private tournament viewing",
    ],
  },
];
